-- Supabase/PostgreSQL table: ha_cars
-- Cars you're considering (Autotrader links, etc.). Run in Supabase SQL Editor.

create table if not exists ha_cars (
  id bigint generated by default as identity primary key,
  link text not null,
  advert_id text,
  title text,
  derivative text,
  make text,
  model text,
  year integer,
  price text,
  price_amount numeric,
  mileage text,
  mileage_amount integer,
  fuel_type text,
  body_type text,
  transmission text,
  colour text,
  engine text,
  owners text,
  registration text,
  seller_name text,
  seller_location text,
  image_url text,
  status text default 'Considering',
  notes text,
  created_at timestamptz default now()
);

comment on table ha_cars is 'Cars shortlist from Autotrader etc.';
comment on column ha_cars.status is 'e.g. Considering, Shortlist, Rejected, Bought';

create index if not exists idx_ha_cars_created_at on ha_cars(created_at desc);
create index if not exists idx_ha_cars_status on ha_cars(status);
create index if not exists idx_ha_cars_advert_id on ha_cars(advert_id);

notify pgrst, 'reload schema';
