-- Supabase/PostgreSQL table: ha_events
-- Run this in the Supabase SQL Editor to create the table.
-- One row per event (concert / comedy / theatre / festival, etc.) attached to a city.

create table if not exists ha_events (
  id bigint generated by default as identity primary key,
  city text not null default 'london',
  type text not null check (type in ('concert', 'comedy', 'theatre', 'festival', 'other')),
  title text not null,
  venue text,
  starts_at timestamptz not null,
  ends_at timestamptz,
  link text,
  map_link text,
  address text,
  latitude double precision,
  longitude double precision,
  notes text,
  status text not null default 'idea' check (status in ('idea', 'booked', 'attended', 'cancelled')),
  attendance text check (attendance is null or attendance in ('going', 'want_to_go')),
  tags text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table ha_events is 'Events (concerts, comedy, theatre, festivals) per city, with status (idea/booked/attended).';
comment on column ha_events.city is 'City slug (e.g. london, new-york, paris).';
comment on column ha_events.type is 'Event type: concert | comedy | theatre | festival | other.';
comment on column ha_events.starts_at is 'Event start time in UTC.';
comment on column ha_events.status is 'idea | booked | attended | cancelled.';
comment on column ha_events.attendance is 'going | want_to_go | null (personal intent).';
comment on column ha_events.map_link is 'Google Maps URL (or any map link).';
comment on column ha_events.address is 'Optional human-readable address.';
comment on column ha_events.latitude is 'WGS84 latitude (auto-extracted from map_link when possible).';
comment on column ha_events.longitude is 'WGS84 longitude (auto-extracted from map_link when possible).';

create index if not exists idx_ha_events_city on ha_events(city);
create index if not exists idx_ha_events_type on ha_events(type);
create index if not exists idx_ha_events_starts_at on ha_events(starts_at);
create index if not exists idx_ha_events_status on ha_events(status);
create index if not exists idx_ha_events_city_starts_at on ha_events(city, starts_at);
create index if not exists idx_ha_events_lat_lng on ha_events(latitude, longitude);

-- RLS: allow the anon key (used by this app's backend) to read/write.
-- Tighten these later if/when auth is added.
alter table ha_events enable row level security;
drop policy if exists "Allow public read access" on ha_events;
drop policy if exists "Allow public write access" on ha_events;
create policy "Allow public read access" on ha_events for select using (true);
create policy "Allow public write access" on ha_events for all using (true) with check (true);
