-- Supabase/PostgreSQL table: ha_houe_ideas
-- Run this in the Supabase SQL Editor to create the table.

create table if not exists ha_house_ideas (
  id bigint generated by default as identity primary key,
  image_name text,
  folder text,
  public_link text,
  bok_like boolean not null default false,
  category text,
  tags text[] default '{}',
  "Room" text,
  style text,
  created_at timestamptz default now()
);

-- Optional: enable RLS (Row Level Security) and add policies as needed
-- alter table ha_house_ideas enable row level security;

comment on table ha_house_ideas is 'House ideas / inspiration images';
comment on column ha_house_ideas.bok_like is 'User liked/bookmarked (default no)';
comment on column ha_house_ideas.tags is 'Array of tags for filtering';
