-- Supabase/PostgreSQL table: ha_jobs_list
-- Run this in the Supabase SQL Editor to create the table.
-- Jobs/tasks management with assignment, due dates, completion status, country, and tags.

create table if not exists ha_jobs_list (
  id bigint generated by default as identity primary key,
  name text not null,
  assigned text,
  date_due date,
  done boolean not null default false,
  country text,
  tags text[] default '{}',
  notes text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table ha_jobs_list is 'Jobs/tasks list with assignment, due dates, completion status, country, and tags';

-- Create indexes for better query performance
create index if not exists idx_ha_jobs_list_assigned on ha_jobs_list(assigned);
create index if not exists idx_ha_jobs_list_date_due on ha_jobs_list(date_due);
create index if not exists idx_ha_jobs_list_done on ha_jobs_list(done);
create index if not exists idx_ha_jobs_list_country on ha_jobs_list(country);
create index if not exists idx_ha_jobs_list_created_at on ha_jobs_list(created_at desc);

-- If the table already exists without notes, add the column in Supabase SQL Editor:
-- alter table ha_jobs_list add column if not exists notes text;

-- Optional: enable RLS (Row Level Security) and add policies as needed
-- alter table ha_jobs_list enable row level security;
-- create policy "Allow public read access" on ha_jobs_list for select using (true);
-- create policy "Allow public write access" on ha_jobs_list for all using (true);
