-- Supabase/PostgreSQL table: ha_jobs_seen
-- Run this in the Supabase SQL Editor to create the table.
-- "Jobs I've seen" – roles you've found (title, company, link, source, notes).

create table if not exists ha_jobs_seen (
  id bigint generated by default as identity primary key,
  title text not null,
  company text,
  link text,
  source text,
  notes text,
  created_at timestamptz default now()
);

comment on table ha_jobs_seen is 'Job listings you have seen – title, company, link, source, notes';

create index if not exists idx_ha_jobs_seen_created_at on ha_jobs_seen(created_at desc);
create index if not exists idx_ha_jobs_seen_company on ha_jobs_seen(company);
