-- Supabase/PostgreSQL table: ha_products
-- Run this in the Supabase SQL Editor to create the table.
-- Products can be linked (e.g. Amazon); we store link, image, price, category, room, tags.

create table if not exists ha_products (
  id bigint generated by default as identity primary key,
  link text not null,
  image_url text,
  price text,
  title text,
  category text,
  room text,
  website_name text,
  tags text[] default '{}',
  created_at timestamptz default now()
);

comment on table ha_products is 'Products to buy (e.g. Amazon links) with image, price, category, room, website_name, tags';

-- If table already exists, add the column:
-- alter table ha_products add column if not exists website_name text;
