-- Supabase/PostgreSQL: Room ideas/notes (free-form ideas per room).
-- Run in Supabase SQL Editor.

create table if not exists ha_room_ideas (
  id bigint generated by default as identity primary key,
  room text not null,
  idea text not null,
  image_url text,
  tags text[] default '{}',
  created_at timestamptz default now()
);

comment on table ha_room_ideas is 'Ideas/notes per room: idea text, optional image link, tags';

create index if not exists idx_ha_room_ideas_room on ha_room_ideas(room);
create index if not exists idx_ha_room_ideas_created_at on ha_room_ideas(created_at desc);
