-- Supabase/PostgreSQL table: ha_things_to_do
-- Run this in the Supabase SQL Editor to create the table.
-- Curated places / experiences worth visiting in a given city (museums, restaurants, parks, etc.).

create table if not exists ha_things_to_do (
  id bigint generated by default as identity primary key,
  city text not null default 'london',
  name text not null,
  category text,
  link text,
  map_link text,
  address text,
  latitude double precision,
  longitude double precision,
  notes text,
  booked boolean not null default false,
  attended boolean not null default false,
  last_visited date,
  tags text[] default '{}',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

comment on table ha_things_to_do is 'Curated things to do per city with booked / attended / last-visited tracking.';
comment on column ha_things_to_do.city is 'City slug (e.g. london, new-york, paris).';
comment on column ha_things_to_do.category is 'Free-text category (Museum, Gallery, Outdoor, Food, Other, …).';
comment on column ha_things_to_do.last_visited is 'Most recent visit date.';
comment on column ha_things_to_do.map_link is 'Google Maps URL (or any map link).';
comment on column ha_things_to_do.address is 'Optional human-readable address.';
comment on column ha_things_to_do.latitude is 'WGS84 latitude (auto-extracted from map_link when possible).';
comment on column ha_things_to_do.longitude is 'WGS84 longitude (auto-extracted from map_link when possible).';

create index if not exists idx_ha_things_to_do_city on ha_things_to_do(city);
create index if not exists idx_ha_things_to_do_category on ha_things_to_do(category);
create index if not exists idx_ha_things_to_do_attended on ha_things_to_do(attended);
create index if not exists idx_ha_things_to_do_booked on ha_things_to_do(booked);
create index if not exists idx_ha_things_to_do_last_visited on ha_things_to_do(last_visited desc);
create index if not exists idx_ha_things_to_do_created_at on ha_things_to_do(created_at desc);
create index if not exists idx_ha_things_to_do_lat_lng on ha_things_to_do(latitude, longitude);

-- RLS: allow the anon key (used by this app's backend) to read/write.
-- Tighten these later if/when auth is added.
alter table ha_things_to_do enable row level security;
drop policy if exists "Allow public read access" on ha_things_to_do;
drop policy if exists "Allow public write access" on ha_things_to_do;
create policy "Allow public read access" on ha_things_to_do for select using (true);
create policy "Allow public write access" on ha_things_to_do for all using (true) with check (true);
