-- Supabase/PostgreSQL table: ha_work_thoughts
-- Run this in the Supabase SQL Editor to create the table.
-- Work / job-search thoughts: comment and category (no DB link to jobs yet).

create table if not exists ha_work_thoughts (
  id bigint generated by default as identity primary key,
  comment text not null,
  category text,
  created_at timestamptz default now()
);

comment on table ha_work_thoughts is 'Work/job-search thoughts: freeform comment and optional category';

create index if not exists idx_ha_work_thoughts_category on ha_work_thoughts(category);
create index if not exists idx_ha_work_thoughts_created_at on ha_work_thoughts(created_at desc);
